name: "Android Build"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      APP_CENTER_TOKEN_ANDROID:
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.4.0
        with:
          provider: aws # default is linode
          region: 'us-east-1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Run S3cmd
        uses: edjufy/s3cmd-github-action@v1.0.2
        with:
          s3cmd_command: 'get s3://pursuit-github/release.keystore android/release.keystore'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
          host_base: 's3.amazonaws.com'
          bucket_location: 'us-east-1'

      #- name: Download release keystore
      #  run: |
      #   s3cmb get s3://pursuit-github/release.keystore android/release.keystore

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Node modules
        run: yarn ci

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command

      - name: Build Android ${{inputs.environment == 'release' && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew bundle${{inputs.environment == 'release' && 'Release' || 'Debug'}} --no-daemon --info --stacktrace

      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pursuit.aab
          path: "android/app/build/outputs/bundle/release/app-release.aab"

  publish-to-appcenter:
    if: ${{ inputs.publish == true }}
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Pursuit.aab
          path: "android/"

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: Ruijan/Pursuit
          token: ${{secrets.APP_CENTER_TOKEN_ANDROID}}
          group: Testers
          file: android/app-release.aab
          notifyTesters: true
          debug: false
