name: Develop Updated
on:
  push:
    branches: [develop]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: "Automated Version Bump"
        uses: "paramsinghvc/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag-prefix: "v"
          tag-suffix: "dev"

      - name: "Sync React Native version with package.json version"
        run: npx react-native-version

      - name: "Commit version sync changes"
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: react native - android & ios versions updated"

      - name: "Automated Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.TOKEN_GITHUB }}
          automatic_release_tag: "latest"
          title: Build

  build-and-release-android:
    needs: versioning
    uses: ./.github/workflows/android-build.yml
    with:
      environment: release
      publish: true
    secrets: inherit
